image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/


stages:
  - test

before_script:
  - apt-get update && apt-get --yes install libsndfile1
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -e .
  - pip install -r speech_requirements.txt
  - curdir=$(pwd) && cd ..
  - rm -rf SimulEval
  - git clone https://github.com/facebookresearch/SimulEval.git/
  - cd SimulEval
  - git checkout 844e4bf62cb4031b4d49247b9520a9966416eea3
  - pip install -e .
  - cd $curdir

test:
  stage: test
  script:
    - python -m unittest discover -s fbk_uts -p "*.py"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'